import asyncio
import pandas as pd
import logging
import os
from datetime import datetime, timezone
from sqlalchemy.orm import Session
from app.db.connection import SessionLocal
from app.models.models import Pool, WaterMeasurement
from app.services.engine import risk_engine

logger = logging.getLogger(__name__)


class SimulationService:
    """
    IoT Water Sensor Simulation Service - CSV-Based Data Playback
    
    This service reads realistic aquaculture data from aquaculture_v2.csv
    (generated by data_gen.py using physics-based simulation) and inserts
    it into the database at configurable intervals.
    
    Configuration Variables:
    - INTERVAL_SECONDS: Time between data insertions (default: 300 = 5 minutes)
    - CSV_PATH: Path to the aquaculture data CSV file
    
    The service cycles through the CSV data sequentially, providing realistic
    patterns including:
    - Diurnal temperature cycles
    - Rain events and their impact on water quality
    - Feeding time effects
    - Oxygen crash scenarios
    - Natural parameter fluctuations
    """
    
    # ==================== CONFIGURATION ====================
    # Change these variables to adjust simulation behavior
    
    INTERVAL_SECONDS = 60  # Time between data insertions (seconds)
                            # 300 = 5 minutes
                            # 60 = 1 minute
                            # 600 = 10 minutes
    
    CSV_PATH = "app/data/aquaculture_v2.csv"  # Path to CSV data file
    
    # ======================================================

    def __init__(self):
        self.running = False
        self.task = None
        self.csv_data = None
        self.current_index = 0
        self._load_csv_data()

    def _load_csv_data(self):
        """Load CSV data on initialization"""
        try:
            if os.path.exists(self.CSV_PATH):
                self.csv_data = pd.read_csv(self.CSV_PATH)
                logger.info(f"📊 Loaded {len(self.csv_data)} rows from {self.CSV_PATH}")
            else:
                logger.error(f"❌ CSV file not found: {self.CSV_PATH}")
                self.csv_data = None
        except Exception as e:
            logger.exception(f"Error loading CSV data: {e}")
            self.csv_data = None

    async def start(self):
        if self.running:
            return
        self.running = True
        logger.info(
            f"🌊 Simulation Service STARTED "
            f"(interval: {self.INTERVAL_SECONDS}s, "
            f"data source: {'CSV' if self.csv_data is not None else 'RANDOM'})"
        )
        self.task = asyncio.create_task(self._run_loop())

    async def stop(self):
        self.running = False
        if self.task:
            self.task.cancel()
            try:
                await self.task
            except asyncio.CancelledError:
                pass
        logger.info("🛑 Simulation Service STOPPED")

    async def _run_loop(self):
        while self.running:
            try:
                self._generate_for_all_pools()
            except Exception as e:
                logger.exception(f"Simulation loop error: {e}")
            await asyncio.sleep(self.INTERVAL_SECONDS)

    # ===================== CORE LOGIC =====================

    def _generate_for_all_pools(self):
        db: Session = SessionLocal()
        try:
            pools = db.query(Pool).all()
            if not pools:
                return

            now = datetime.now(timezone.utc)

            for pool in pools:
                # Get data from CSV or use fallback
                data = self._get_next_csv_row()

                measurement = WaterMeasurement(
                    pool_id=pool.pool_id,
                    temperature=round(data["temperature"], 2),
                    ph=round(data["ph"], 2),
                    dissolved_oxygen=round(data["dissolved_oxygen"], 2),
                    amonia=round(data["ammonia"], 4),
                    turbidity=round(data["turbidity"], 2),
                    created_at=now,
                )
                db.add(measurement)

            db.commit()
            logger.info(
                f"✅ Generated data for {len(pools)} pools at {now.strftime('%H:%M:%S')} UTC "
                f"(CSV row {self.current_index}/{len(self.csv_data) if self.csv_data is not None else 'N/A'})"
            )

        except Exception as e:
            db.rollback()
            logger.exception(f"DB error in simulation: {e}")
        finally:
            db.close()

    # ===================== CSV DATA HANDLING =====================

    def _get_next_csv_row(self):
        """
        Get the next row from CSV data and cycle back to start when reaching the end.
        Falls back to default values if CSV is not available.
        """
        if self.csv_data is None or len(self.csv_data) == 0:
            # Fallback to default values if CSV not available
            return {
                "temperature": 28.0,
                "ph": 7.5,
                "dissolved_oxygen": 6.5,
                "ammonia": 0.05,
                "turbidity": 30.0,
            }

        # Get current row
        row = self.csv_data.iloc[self.current_index]

        # Advance to next row and cycle if needed
        self.current_index = (self.current_index + 1) % len(self.csv_data)

        # Extract values from CSV
        return {
            "temperature": float(row["temperature"]),
            "ph": float(row["ph"]),
            "dissolved_oxygen": float(row["dissolved_oxygen"]),
            "ammonia": float(row["ammonia"]),
            "turbidity": float(row["turbidity"]),
        }

    # ===================== PUBLIC API =====================

    def seed_new_pool(self, pool_id):
        """Seed a new pool with initial data from CSV"""
        db: Session = SessionLocal()
        try:
            pool = db.query(Pool).filter(Pool.pool_id == pool_id).first()
            if not pool:
                return

            # Get initial data from CSV
            data = self._get_next_csv_row()

            measurement = WaterMeasurement(
                pool_id=pool.pool_id,
                temperature=data["temperature"],
                ph=data["ph"],
                dissolved_oxygen=data["dissolved_oxygen"],
                amonia=data["ammonia"],
                turbidity=data["turbidity"],
                created_at=datetime.now(timezone.utc),
            )
            db.add(measurement)
            db.commit()
            logger.info(f"🌱 Seeded initial data for pool {pool_id}")

        except Exception as e:
            db.rollback()
            logger.exception(f"Seed new pool error: {e}")
        finally:
            db.close()

    def set_interval(self, seconds: int):
        """
        Dynamically change the data insertion interval.
        Note: Takes effect after the current interval completes.
        
        Args:
            seconds: New interval in seconds (minimum 1)
        """
        if seconds < 1:
            logger.warning("Interval must be at least 1 second")
            return
        
        old_interval = self.INTERVAL_SECONDS
        self.INTERVAL_SECONDS = seconds
        logger.info(f"⏱️ Interval changed from {old_interval}s to {seconds}s")

    def reset_csv_position(self):
        """Reset CSV reading position to the beginning"""
        self.current_index = 0
        logger.info("🔄 CSV position reset to beginning")


# Singleton
simulation_service = SimulationService()