import pandas as pd
import numpy as np
from xgboost import XGBRegressor
import joblib
import os

# =========================
# CONFIG
# =========================
DATA_PATH = "../data/aquaculture_v2.csv" # Or your generated file
MODEL_DIR = "../models_storage"
os.makedirs(MODEL_DIR, exist_ok=True)

# CONFIGURATION FOR 30-MINUTE PREDICTION
FREQ_MINUTES = 5
PREDICT_MINUTES = 30
STEPS_AHEAD = int(PREDICT_MINUTES / FREQ_MINUTES) # 30 / 5 = 6 steps

print(f"Configuring for {PREDICT_MINUTES} minute prediction ({STEPS_AHEAD} steps ahead).")

# LOAD
print("Loading data...")
df = pd.read_csv(DATA_PATH)
df["timestamp"] = pd.to_datetime(df["timestamp"])

target_cols = ["dissolved_oxygen", "ph", "ammonia", "turbidity", "temperature"]

# =========================
# 1. FEATURE ENGINEERING
# =========================

# A. TARGET CREATION: Predict the DELTA (Future - Current)
# It is better to predict the *change* than the absolute number for longer horizons.
for col in target_cols:
    # Future value (for reference/checking)
    df[f"{col}_future"] = df[col].shift(-STEPS_AHEAD)
    
    # ACTUAL TARGET: How much will the value change in 30 mins?
    df[f"{col}_target"] = df[col].shift(-STEPS_AHEAD) - df[col]

# B. INPUT FEATURES
# Since we predict 30 mins out, we need to look back at least that far.
# Windows: 3 (15m), 6 (30m), 12 (60m), 24 (2 hours)
windows = [3, 6, 12, 24] 

for col in target_cols:
    for w in windows:
        # Rolling Mean (Trend)
        df[f"{col}_roll_mean_{w}"] = df[col].rolling(window=w).mean()
        
        # Rolling Std (Volatility - important for crash detection)
        df[f"{col}_roll_std_{w}"] = df[col].rolling(window=w).std()
        
        # Current Trend (Current - Value W steps ago)
        df[f"{col}_trend_{w}"] = df[col] - df[col].shift(w)

# Time info (Cyclical features are better for ML)
df["hour_sin"] = np.sin(2 * np.pi * df["timestamp"].dt.hour / 24)
df["hour_cos"] = np.cos(2 * np.pi * df["timestamp"].dt.hour / 24)
df["month"] = df["timestamp"].dt.month

# Clean NaNs generated by shifting and rolling
df = df.dropna()

# =========================
# 2. DEFINE FEATURES LIST
# =========================
feature_cols = ["rain_event", "feeding_event", "hour_sin", "hour_cos", "month"]

for col in target_cols:
    feature_cols.append(col) # Current Value is the most important baseline
    for w in windows:
        feature_cols.append(f"{col}_roll_mean_{w}")
        feature_cols.append(f"{col}_roll_std_{w}")
        feature_cols.append(f"{col}_trend_{w}")

print(f"Total Features used: {len(feature_cols)}")

# =========================
# 3. TRAIN LOOP
# =========================
X = df[feature_cols]

# Weights: Prioritize dangerous situations
weights = np.ones(len(X))
weights[df["dissolved_oxygen"] < 3.5] = 10.0 
weights[df["ammonia"] > 0.5] = 10.0

for name in target_cols:
    print(f"Training model for {name} (Delta Prediction)...")
    
    # We train on the DELTA target
    y = df[f"{name}_target"]
    
    model = XGBRegressor(
        n_estimators=800,       # Increased estimators for harder problem
        max_depth=7,            # Deeper trees to catch complex lag patterns
        learning_rate=0.03,     # Slower learning rate for better generalization
        objective="reg:squarederror",
        n_jobs=-1
    )
    
    model.fit(X, y, sample_weight=weights)
    
    joblib.dump(model, f"{MODEL_DIR}/xgb_{name}.pkl")
    
joblib.dump(feature_cols, f"{MODEL_DIR}/features.pkl")
print("Training Done. Models saved.")